import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { MainSidebar } from './_components/main-sidebar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-[16rem_1fr]">
          <MainSidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
